# Generated by Django 5.0 on 2024-02-02 09:33

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beadcrumbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Join_Teams', models.IntegerField()),
                ('Total_Play_Games', models.IntegerField()),
                ('Total_Players', models.IntegerField()),
                ('Total_Futsal_Ground', models.IntegerField()),
                ('Total_Winner_Teams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('small_description', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_url', models.CharField(default='location', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='img/')),
                ('email', models.EmailField(max_length=800)),
                ('website', models.CharField(max_length=100)),
                ('footer_description', models.TextField(default='location', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=600)),
                ('image', models.ImageField(default='img/testimonial.jpg', null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Book_futsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(choices=[(datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '13:00 PM'), (datetime.time(14, 0), '14:00 PM'), (datetime.time(15, 0), '15:00 PM'), (datetime.time(16, 0), '16:00 PM'), (datetime.time(17, 0), '17:00 PM')])),
                ('duration', models.PositiveIntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours'), (5, '5 hours')], default=1)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.futsal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.futsal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('first_image', models.ImageField(null=True, upload_to='img/')),
                ('second_image', models.ImageField(null=True, upload_to='img/')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('playercount', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14'), ('16', '16')], default='5', max_length=150)),
                ('gametype', models.CharField(choices=[('friendly match', 'friendly match'), ('losers match', 'losers match')], default='friendly match', max_length=150)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='booking.team')),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.futsal')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='booking.team')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.futsal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
