# Generated by Django 5.0 on 2024-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='playercount',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14'), ('16', '16'), ('20', '20')], default='5', max_length=150),
        ),
    ]
