# Generated by Django 5.0 on 2024-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
